### ISSUE TITLE
Difficulties with recent Debian/Gitea versions

### ISSUE THREAD

**Issue by blhiggins** [flobee/gitea-installer#1]
Hello,

I recently used these scripts to install a new instance of Gitea 1.19.3 on Debian Bookworm running on RaspberryPi 4 (64bit) hardware. I succeeded eventually, but not without some hiccups (sorry for posting multiple issues together - I have limited time):
* Backup fails and generates mess if "git" user not yet created; backup is enabled by default but should be disabled on first install
* arm64 build isn't part of the default list of binaries in config.sh-dist
* sha256sum complains about missing file after download (possible silent failure here?)
* install.sh creates some folders and forgets to chown them to "git" user
* On first gitea start: "...s/setting/setting.go:186:SetCustomPathAndConf() [W] Using 'custom' directory as relative origin for configuration file: '/home/git/tea/custom/custom/conf/app.ini'": this causes the initial configuration file to be written to the wrong location (note the double "custom/" in the message).
* If you do "chmod 750 /home/git/tea/custom/conf/", "chmod 640 /home/git/tea/custom/conf/app.ini", and "chown -R root:git /home/git/tea/custom/conf/" as the script advises, gitea will fail to start; log says "...s/setting/setting.go:369:CreateOrAppendToCustomConf() [F] error saving to custom config: open /home/git/tea/custom/conf/app.ini: permission denied". Fixed this by chowning back to user "git".

I addressed each of those problems as I went, and now have a working Gitea server. Thanks for your helpful scripts!

Best,
Brendon

**Comment by flobee** [comment]
Hi
thx for info. thx that you like the helper :-)

can not reproduce until i have your config and shell output. form first install!
most of the things do not make sence for me or handeld in task I=Install or U Update. U for Install would do some things you reported here.
