### ISSUE TITLE
download.sh does not check SHA256 hashes properly, failing silently

### ISSUE THREAD

**Issue by blhiggins** [flobee/gitea-installer#2]
Hello, it's me again. I have a more specific issue for you this time, encountered during an update run. When I ran `sudo ./update.sh` I saw this:
```
Download url: 'https://dl.gitea.com/gitea/1.20.5/gitea-1.20.5-linux-arm64'
Download sources now? (defaut: 'Y')
Confirm (Y)es,(n)o (def:'Y'): 
/tmp/latest                  100%[=============================================>] 121.93M  5.55MB/s    in 22s     
/tmp/latest.sha256           100%[=============================================>]      91  --.-KB/s    in 0s      
Download checksum check...
sha256sum: gitea-1.20.5-linux-arm64: No such file or directory
OK
# install binary
---------------------------------------------------------------------
If you dont see any erros.. the service was removed, re-added and
gitea was started again. (If you run this script e.g for updates)

NOTE: gitea app.ini is temporary set with write rights for user git so that the
Web installer could write the configuration file.
After installation is done it is recommended to set rights to read-only to keep
the config secure. Please run:

    chmod 750 /home/git/tea/custom/conf/
    chmod 640 /home/git/tea/custom/conf/app.ini
    chown -R root:git /home/git/tea/custom/conf/

To check if the service is runing:
    systemctl status gitea.service

Checking migration status:
    tail -f /home/git/tea/log/gitea.log

Happy git + tea :)
```

Notice these lines in particular:
```
Download checksum check...
sha256sum: gitea-1.20.5-linux-arm64: No such file or directory
OK
```

So the update script attempts to check the SHA256 hash, fails, and then continues anyway. This surely is not intended behaviour?

Inside the `download.sh` script, it says this:
```
if [ `sha256sum --status -c "${GITEA_BIN_BASENAME}.sha256"` ]; then
    echo 'Checksum error';
    exit 1;
else
    echo "OK";
fi
```

There are two problems. The first is that the logic in the above `if` is inverted: `sha256sum --status -c` will return success (0) if it finds the file and its hash matches, and in that case it will hit the 'Checksum error' condition. Only if the `sha256sum` call fails to match the hash will it hit the "OK" condition. Easy solution is to switch the positions of the two outcomes.

The second problem is that the `sha256sum` program assumes the file will have the same name as it does in the hash file, i.e. the same name as on the server. But `download.sh` saves the file to `latest` (and the hash to `latest.sha256`). This seems to be a consequence of `GITEA_BIN_BASENAME` being defined in `config.sh-dist`, which is invoked prior to `config.sh`, and thus any variables which depend on fields changed by `config.sh` will not be updated. Solving this might need a little bit of refactoring so that dependent variables wait until `config.sh` is loaded before being defined. Or (possibly) `download.sh` does not override the output file name from what the server calls the file.

**Comment by blhiggins** [comment]
Actually, now I'm looking at this `if` line more closely... I think the backticks are messing it up. Consider, try running this:
```
if [ `false` ]; then echo 'true'; else echo 'false'; fi
if [ `true` ]; then echo 'true'; else echo 'false'; fi
false
echo $?
true
echo $?
```

The result I get is that _both_ if calls will yield the false condition!

I think the correct solution (to problem one) might actually be more like this:
```
if sha256sum --status -c "${GITEA_BIN_BASENAME}.sha256"; then
```

**Comment by flobee** [comment]
Hi and thanks for the report.

Well... i can not really reproduce it :-(

Example piping in your url:
```
./update.sh https://dl.gitea.com/gitea/1.20.5/gitea-1.20.5-linux-arm64
Download url: 'https://dl.gitea.io/gitea/1.20.5/gitea-1.20.5-linux-amd64'
-----------------------------------------------------------------^^^^^^ rewrite: its based on the runnng OS
----------------------------------------------------------------- from config.sh-dist BUT: there seems to be the
----------------------------------------------------------------- handling bug. it should force using the given url. 
----------------------------------------------------------------- e.g. with a warning if OS differs -> missing

Download sources now? (defaut: 'Y')
Confirm (Y)es,(n)o (def:'Y'): 

GITEA_BIN_URL: 'https://dl.gitea.io/gitea/1.20.5/gitea-1.20.5-linux-amd64' 
=>TO=> 
/tmp/gitea-1.20.5-linux-amd64                  
^^^^ DEBUG output. to check what it does

/tmp/gitea-1.20.5-linux-amd64  100%[==============================================...
/tmp/gitea-1.20.5-linux-amd64.sha256  100%[==========================================...
Download checksum check...
OK
```
Even when piping using `./update.sh latest` : it never saves to /tmp/latest.

i will have a look for a fix and also when checking the hashes. 

actually i dont use a local config when testing. have you tested that way?

kind regards

**Comment by blhiggins** [comment]
> actually i dont use a local config when testing. have you tested that way?

I'd rather not run `update.sh` again as it's a production machine, but I did try `sudo sh download.sh https://dl.gitea.com/gitea/1.20.5/gitea-1.20.5-linux-arm64` to see what would happen, and interestingly it also saved those files to `/tmp/latest` and `/tmp/latest.sha256`.

I can see the flow of logic that causes the problem: `download.sh` refers to the `GITEA_BIN_BASENAME` variable when specifying the local file name. This is not `GITEA_BIN_URL`. Where is it defined? It's not defined inside `download.sh`, and doesn't depend on any of the arguments passed to that script.

Seems that `GITEA_BIN_BASENAME` is defined in `config.sh-dist`. I think in your case what happens is that `download.sh` initially calls your `config.sh-dist` which searches for the latest gitea version for your `amd64` architecture, sets `GITEA_BIN_URL` to this URL, then sets `GITEA_BIN_BASENAME` to match that. In my case, `config.sh-dist` doesn't have logic to find the latest for my `arm64` architecture - so it just stays "latest" for `GITEA_BIN_URL` (until I override it in my `config.sh`) and `GITEA_BIN_BASENAME`.

The big problem is that `GITEA_BIN_URL` gets modified after `GITEA_BIN_BASENAME` is defined, and nothing updates `GITEA_BIN_BASENAME` to match what `GITEA_BIN_URL` changes to.

If I'm right, and assuming download.sh is fixed to respect the command-line argument, then I predict that you could pass any URL on the command line to `download.sh`, and the destination filename it saves that file to still would never be different.

For my own workaround, I'll just copy `config.sh-dist` to `config.sh` in its entirety, then replace `GITEA_BIN_URL` with the actual URL before `GITEA_BIN_BASENAME` is defined (i.e., in the regular place).

Best regards

**Comment by flobee** [comment]
All correct but if you dont share all of your code.. /tmp/latest[.sha*] is not what the scripts are doing. impossible. standard locations dont use a url of basename latest.

and yes: sharing of the variables cross the scripts are the problem. i'm still thinking for a better solution without a rewrite. next update will report more and exits more early.

i'm using it in production with the runner.sh to save my time with 'latest' and it just run/work since ages.

you may use 'config.sh.example-for-your-setup' and only edit it to your needs. 
coping the complete dist file is not a part of suggested option and has side effects on top. check the inline comments.

```
./download.sh https://dl.gitea.com/gitea/1.20.5/gitea-1.20.5-linux-arm64
Download url: 'https://dl.gitea.io/gitea/1.20.5/gitea-1.20.5-linux-amd64'
Download sources now? (defaut: 'Y')
Confirm (Y)es,(n)o (def:'Y'): Y
/tmp/gitea-1.20.5-linux-amd64                    27%[=====
```
just downloads it, checks hashes, done. point :-)

**Comment by flobee** [comment]
pls check if some of it works better: https://github.com/flobee/gitea-installer/commit/ee31971001f165ff4112be4bf7615e6467196683

i would like to suggest using the runner.sh for all!

replace your config.sh with defaults of: `config.sh.example-for-your-setup`

thx

**Comment by flobee** [comment]
Added new Version: 2.0.0 with losts of improvements

see: https://github.com/flobee/gitea-installer/releases/tag/2.0.0
